### ISSUE TITLE
Register Redirect Model as a Sylius Resource for Better Extensibility

### ISSUE THREAD

**Issue by bouriau** [Setono/SyliusRedirectPlugin#123]
Hi, unless I'm mistaken, the Redirect model is not fully declared as a Sylius resource, which makes it harder to extend and customize.

Sylius provides an efficient way to make resources easy to customize, but it seems this plugin does not use it.

In my case, I need to add some custom logic. Thanks to Symfony, it's always possible to customize parts of a bundle, but it can be a bit tricky and frustrating at times. Additionally, this can complicates maintainability.

What do you think about registering the Redirect model as a Sylius resource, then it would be easier to extends and customize it?

``` yaml
# /src/Resources/config/app/config.yaml
imports:
    - { resource: resources.yaml }
    # - { other imports}
```

``` yaml
# /src/Resources/config/app/resources.yaml
imports:
    - { resource: SetonoSyliusRedirectPlugin/Resources/config/resources/redirect.yaml }
    # - { other imports}
```
``` yaml
# /src/Resources/config/resources/redirect.yaml
sylius_resource:
    resources:
        setono_sylius_redirect.redirect:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusRedirectPlugin\Model\Redirect
                interface: Setono\SyliusRedirectPlugin\Model\RedirectInterface
                form: Setono\SyliusRedirectPlugin\Form\Type\RedirectType
                repository: Setono\SyliusRedirectPlugin\Repository\RedirectRepository
                factory: Setono\SyliusRedirectPlugin\Factory\RedirectFactory
```
