### ISSUE TITLE
Easier configuration of automatic redirects

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusRedirectPlugin#63]
Right now the automatic redirect feature is maybe too complicated: It involves form extensions and javascript. What if we could just enable it by config like so:

```yaml
setono_sylius_redirect:
    automatic_redirects:
        - 'sylius.product_translation'
        - 'sylius.taxon_translation'
```

where `sylius.product_translation` and `sylius.taxon_translation` are the resources defined by Sylius.

Of course this would create more redirects than necessary, but if people have implemented the cronjob to remove redirects that aren't accessed, that wouldn't be a problem.
